include:
  - template: Container-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

container_scanning:
  stage: Security
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE
    CI_APPLICATION_TAG: $CI_COMMIT_SHA

dependency_scanning:
  stage: Security

sast:
  stage: Security

license_scanning:
  stage: Security
